services: 
  deploy:
    image: phish108/ansible:10.0.1-1
    restart: no
    volumes:
      - ./:/ansible
      - ~/.autossh:/sshkeys
      - ../deployment-configs:/configs
      - ../inventory-docker:/inventory
