- name: setup edge proxy service with SDG
  # speed things up
  gather_facts: false
  hosts: mainnode

  tasks:
  - name: load packages from config
    include_vars:
      file: /configs/configs.yaml
      name: sdg_config

  - name: load container sha from config
    include_vars:
      file: ./configs/containers.yaml
      name: cicd

  # Setup External Networks
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_network_module.html

  - name: setup caddyadmin network
    docker_network:
      name: "{{ item }}"
      attachable: true
      internal: false
      driver: overlay
      driver_options: 
        encrypted: ""
      state: present
    with_items: "{{ sdg_config.networks }}"

  # Setup Configs
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_config_module.html

  - name: setup proxy configs
    register: proxyconfig
    docker_config:
      name: proxy_caddyfile
      data: "{{ lookup('file', '/configs/Caddyfile' ) }}"
      rolling_versions: true
      versions_to_keep: 2
      state: present
   
  - name: setup authomator configs
    register: authoconfig
    docker_secret:
      name: autho_config
      data: "{{ lookup('file', '/configs/authomator_config.yaml' ) }}"
      rolling_versions: true
      versions_to_keep: 2
      state: present

  - name: setup ad-resolver configs
    register: adresolver_config
    docker_secret:
      name: adresolver_config
      data: "{{ lookup('file', '/configs/ad_resolver.json' ) | from_json | to_json }}"
      rolling_versions: true
      versions_to_keep: 2
      state: present

  - name: setup dashboard configs
    register: sdgwebconfig
    docker_config:
      name: sdgweb_config
      data: "{{ lookup('file', './configs/dashboard_config.json' ) | from_json | to_json }}"
      rolling_versions: true
      versions_to_keep: 2
      state: present

  # Deploy the content Services

  - name: deploy dgraph
    environment:
      HOST_CONSTRAINT: "{{ sdg_config.dgraph.constraints.host }}"
    docker_stack:
      name: dgraph
      state: present
      prune: true
      compose: 
      - "{{ lookup('file', './services/stack-dgraph_standalone.yaml' ) | from_yaml }}"
  
  - name: deploy sdg frontend stack from file
    environment:
      CONFIGNAME: "{{ sdgwebconfig.config_name }}"
      IMAGETAG: "sha-{{ cicd.containers.dashboard_sha }}"
    docker_stack:
      name: sdgfrontend
      state: present
      # Prune means that only services in the stack definition are present. Older services will be automatically removed.
      prune: true
      compose: 
      - "{{ lookup('file', './services/stack-sdgfrontend.yaml' ) | from_yaml }}"

  # Deploy the authentication Service
  - name: deploy authomator middleware stack from file
    # The environment variable tells docker_stack any changed CONFIGNAME
    environment:
      CONFIGNAME: "{{ authoconfig.secret_name }}"
      IMAGETAG: "sha-{{ cicd.containers.authomator_sha }}"
    docker_stack:
      name: autho
      state: present
      prune: true
      compose: 
      - "{{ lookup('file', './services/stack-authomator.yaml' ) | from_yaml }}"

  # Deploy the Service
  - name: deploy reverse proxy stack from file
    # The environment variable tells docker_stack any changed CONFIGNAME
    # 
    environment:
      CONFIGNAME: "{{ proxyconfig.config_name }}"
    docker_stack:
      name: web
      state: present
      # Prune means that only services in the stack definition are present. Older services will be automatically removed.
      prune: true
      compose: 
      - "{{ lookup('file', './services/stack-reverse-proxy.yaml' ) | from_yaml }}"
