services:
  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    networks:
      - servicenet
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == ${DBHOST_CONSTRAINT}
  
  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:${DBINIT_SHA}
    networks:
      - servicenet
    environment:
      TIMEOUT: 20
      DGRAPH_SERVER: http://db:8080
    deploy:
      restart_policy:
        condition: none
 
  mq: 
    image: rabbitmq:3.12.8-alpine
    networks:
      - servicenet
    configs:
    - source: mq_main_config
      target: /etc/rabbitmq/rabbitmq.conf
    - source: mq_queue_config
      target: /etc/rabbitmq/definitions.d/02-queues-exchanges.json
    secrets:
    - source: mq_user_config
      target: /etc/rabbitmq/definitions.d/00-users.json

networks:
  servicenet:
    external: true
    name: ${STACK_NETWORK}

volumes:
  dgraph:
    external: true
    name: dgraph

configs:
  mq_main_config:
    external: true
    name: ${MQ_MAIN_CONFIG}
  mq_queue_config:
    external: true
    name: ${MQ_QUEUE_CONFIG}

secrets: 
  mq_user_config:
    external: true
    name: ${MQ_USER_CONFIG}