version: "3.8"
services:
  indexer:
    image: ghcr.io/sustainability-zhaw/sdg-indexer:${IMAGETAG}
    networks:
      - sdgservices
    configs:
      - source: resolver_config
        target: /etc/app/config.json

networks: 
  sdgservices: 
    external: true

configs: 
  resolver_config:
    external: true
    name: ${CONFIGNAME}
    