version: "3.8"
services:
  indexer:
    image: ghcr.io/sustainability-zhaw/sdg-indexer:${IMAGETAG}
    restart: unless-stopped
    networks:
      - sdgservices
    environment:
      DB_HOST: ${CONFIG_DB_HOST}
      BATCH_SIZE: ${CONFIG_BATCH_SIZE}
      BATCH_INTERVAL: ${CONFIG_BATCH_INTERVAL}

networks: 
  sdgservices: 
    external: true
