version: "3.8"
services:
  standalone:
    image: dgraph/standalone:v22.0.2
    # restart: always
    networks:
      - sdgservices
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOST_CONSTRAINT}

  initializer: 
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-${DB_INIT}
    # restart: "no"
    networks:
      - sdgservices
    deploy:
      restart_policy:
        condition: none

    environment:
      TIMEOUT: 20
      DGRAPH_SERVER: http://dgraph_standalone:8080

networks: 
  sdgservices: 
    external: true
 
volumes:
  dgraph:
    external: true
    name: dgraph
    