containers:
  dashboard_sha: a68b4e4
  adresolver_sha: b73cba8
  schema_sha: c55b434
  authomator_sha: df07b2d
  dspace_sha: e48a854
  evento_sha: d58f8d3
  sdgindexer_sha: '5419011'
  keywords: e377c74
