containers:
  dashboard_sha: 0dc17b7
  adresolver_sha: abbee7e
  schema_sha: cd0f0d0
  authomator_sha: df07b2d
  dspace_sha: '7735624'
  evento_sha: 49ca18e
  sdgindexer_sha: cc8c0fb
  keywords: 7dc5aca
